/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw;
typedef struct tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw;
typedef struct tyObject_st_rcc_MuzeLgc5IKig8i4T9bW3EeA tyObject_st_rcc_MuzeLgc5IKig8i4T9bW3EeA;
typedef struct tyObject_st_nvic_89cdN5dIxFWwR88uhxVZzLw tyObject_st_nvic_89cdN5dIxFWwR88uhxVZzLw;
struct tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw {
NU32 CR1;
NU32 CR2;
NU32 SMCR;
NU32 DIER;
NU32 SR;
NU32 EGR;
NU32 CCMR1;
NU32 CCMR2;
NU32 CCER;
NU32 CNT;
NU32 PSC;
NU32 ARR;
NU32 RSV1;
NU32 CCR1;
NU32 CCR2;
NU32 CCR3;
NU32 CCR4;
NU32 RSV2;
NU32 DCR;
NU32 DMAR;
};
struct tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw {
NU32 MODER;
NU32 OTYPER;
NU32 OSPEEDR;
NU32 PUPDR;
NU32 IDR;
NU32 ODR;
NU32 BSRR;
NU32 LCKR;
NU32 AFRL;
NU32 AFRH;
NU32 BRR;
};
struct tyObject_st_rcc_MuzeLgc5IKig8i4T9bW3EeA {
NU32 CR;
NU32 CFGR;
NU32 CIR;
NU32 APB2RSTR;
NU32 APB1RSTR;
NU32 AHBENR;
NU32 APB2ENR;
NU32 APB1ENR;
NU32 BDCR;
NU32 CSR;
NU32 AHBRSTR;
NU32 CFGR2;
NU32 CFGR3;
};
typedef NU32 tyArray_MpWsq9bBH14GsDQQ59cgyxAQ[8];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef NU32 tyArray_w1HrpLTqYuul17OlwTATGw[56];
typedef NU8 tyArray_wknELTfNGbUq9aI09bLKcmWQ[240];
typedef NU32 tyArray_skVRt9aMy4p9aFnOi3BwXnJw[644];
struct tyObject_st_nvic_89cdN5dIxFWwR88uhxVZzLw {
tyArray_MpWsq9bBH14GsDQQ59cgyxAQ ISER;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig RSV1;
tyArray_MpWsq9bBH14GsDQQ59cgyxAQ ISCR;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig RSV2;
tyArray_MpWsq9bBH14GsDQQ59cgyxAQ ISPR;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig RSV3;
tyArray_MpWsq9bBH14GsDQQ59cgyxAQ ICPR;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig RSV4;
tyArray_MpWsq9bBH14GsDQQ59cgyxAQ IABR;
tyArray_w1HrpLTqYuul17OlwTATGw RSV5;
tyArray_wknELTfNGbUq9aI09bLKcmWQ IP;
tyArray_skVRt9aMy4p9aFnOi3BwXnJw RSV6;
NU32 STIR;
};
N_NIMCALL(void, TIM2_IRQHandler)(void);
N_LIB_PRIVATE N_NIMCALL(void, mainProc2_rbimN4ouysYCcQ9cvzq9cqUA)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_stm32Init000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_stm32DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_volatileInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_volatileDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void);

N_NIMCALL(void, TIM2_IRQHandler)(void) {
	{
		NU32 res;
		NU32 res_2;
		res = (NU32)0;
		res = (*(NU32 volatile*)(&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).SR));
		if (!!(((NU32)(res & ((NI) 2)) == ((NI) 0)))) goto LA3_;
		*((NU32 volatile*)((&(*((tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw*) 1207959552)).ODR))) = ((NI) 1);
		res_2 = (NU32)0;
		res_2 = (*(NU32 volatile*)(&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).SR));
		*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).SR))) = (NU32)(res_2 & (NU32)((NU32) ~(((NU32) (((NI) 2))))));
	}
	LA3_: ;
	{
		NU32 res_3;
		NU32 res_4;
		res_3 = (NU32)0;
		res_3 = (*(NU32 volatile*)(&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).SR));
		if (!!(((NU32)(res_3 & ((NI) 1)) == ((NI) 0)))) goto LA7_;
		*((NU32 volatile*)((&(*((tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw*) 1207959552)).ODR))) = ((NI) 0);
		res_4 = (NU32)0;
		res_4 = (*(NU32 volatile*)(&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).SR));
		*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).SR))) = (NU32)(res_4 & (NU32)((NU32) ~(((NU32) (((NI) 1))))));
	}
	LA7_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, mainProc2_rbimN4ouysYCcQ9cvzq9cqUA)(void) {
	NU32 res;
	NU32 res_2;
	NU32 res_3;
	NU32 res_4;
	res = (NU32)0;
	res = (*(NU32 volatile*)(&(*((tyObject_st_rcc_MuzeLgc5IKig8i4T9bW3EeA*) 1073876992)).AHBENR));
	*((NU32 volatile*)((&(*((tyObject_st_rcc_MuzeLgc5IKig8i4T9bW3EeA*) 1073876992)).AHBENR))) = (NU32)(res | ((NU32) (((NI) 131072))));
	res_2 = (NU32)0;
	res_2 = (*(NU32 volatile*)(&(*((tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw*) 1207959552)).MODER));
	*((NU32 volatile*)((&(*((tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw*) 1207959552)).MODER))) = (NU32)(res_2 | ((NU32) (((NI) 1))));
	res_3 = (NU32)0;
	res_3 = (*(NU32 volatile*)(&(*((tyObject_st_rcc_MuzeLgc5IKig8i4T9bW3EeA*) 1073876992)).APB1ENR));
	*((NU32 volatile*)((&(*((tyObject_st_rcc_MuzeLgc5IKig8i4T9bW3EeA*) 1073876992)).APB1ENR))) = (NU32)(res_3 | ((NU32) (((NI) 1))));
	*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).CR1))) = ((NI) 129);
	*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).DIER))) = ((NI) 3);
	*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).PSC))) = ((NI) 8000);
	*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).ARR))) = ((NI) 1000);
	*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).CCR1))) = ((NI) 500);
	*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).EGR))) = ((NI) 1);
	res_4 = (NU32)0;
	res_4 = (*(NU32 volatile*)(&(*((tyObject_st_nvic_89cdN5dIxFWwR88uhxVZzLw*) IL64(3758153984))).ISER[(((NI) 0))- 0]));
	*((NU32 volatile*)((&(*((tyObject_st_nvic_89cdN5dIxFWwR88uhxVZzLw*) IL64(3758153984))).ISER[(((NI) 0))- 0]))) = (NU32)(res_4 | ((NU32) (((NI) 268435456))));
	{
		while (1) {
		}
	}
}
void PreMainInner(void) {
	systemInit000();
	unknown_stm32DatInit000();
	stdlib_volatileDatInit000();
	mainDatInit000();
	unknown_stm32Init000();
	stdlib_volatileInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
}

int main(void) {
	NimMain();
	return 0;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	mainProc2_rbimN4ouysYCcQ9cvzq9cqUA();
}

NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void) {
}

