/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw;
typedef struct tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw;
typedef struct tyObject_st_rcc_MuzeLgc5IKig8i4T9bW3EeA tyObject_st_rcc_MuzeLgc5IKig8i4T9bW3EeA;
typedef struct tyObject_st_nvic_89cdN5dIxFWwR88uhxVZzLw tyObject_st_nvic_89cdN5dIxFWwR88uhxVZzLw;
struct tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw {
NU32 CR1;
NU32 CR2;
NU32 SMCR;
NU32 DIER;
NU32 SR;
NU32 EGR;
NU32 CCMR1;
NU32 CCMR2;
NU32 CCER;
NU32 CNT;
NU32 PSC;
NU32 ARR;
NU32 RSV1;
NU32 CCR1;
NU32 CCR2;
NU32 CCR3;
NU32 CCR4;
NU32 RSV2;
NU32 DCR;
NU32 DMAR;
};
typedef NI tyArray_GAcaPw08Gj9cXYhAaMMr9cfw[1];
struct tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw {
NU32 MODER;
NU32 OTYPER;
NU32 OSPEEDR;
NU32 PUPDR;
NU32 IDR;
NU32 ODR;
NU32 BSRR;
NU32 LCKR;
NU32 AFRL;
NU32 AFRH;
NU32 BRR;
};
struct tyObject_st_rcc_MuzeLgc5IKig8i4T9bW3EeA {
NU32 CR;
NU32 CFGR;
NU32 CIR;
NU32 APB2RSTR;
NU32 APB1RSTR;
NU32 AHBENR;
NU32 APB2ENR;
NU32 APB1ENR;
NU32 BDCR;
NU32 CSR;
NU32 AHBRSTR;
NU32 CFGR2;
NU32 CFGR3;
};
typedef NI tyArray_HU7qaqKu9czJLT84iCBJnsA[2];
typedef NU32 tyArray_MpWsq9bBH14GsDQQ59cgyxAQ[8];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef NU32 tyArray_w1HrpLTqYuul17OlwTATGw[56];
typedef NU8 tyArray_wknELTfNGbUq9aI09bLKcmWQ[240];
typedef NU32 tyArray_skVRt9aMy4p9aFnOi3BwXnJw[644];
struct tyObject_st_nvic_89cdN5dIxFWwR88uhxVZzLw {
tyArray_MpWsq9bBH14GsDQQ59cgyxAQ ISER;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig RSV1;
tyArray_MpWsq9bBH14GsDQQ59cgyxAQ ISCR;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig RSV2;
tyArray_MpWsq9bBH14GsDQQ59cgyxAQ ISPR;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig RSV3;
tyArray_MpWsq9bBH14GsDQQ59cgyxAQ ICPR;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig RSV4;
tyArray_MpWsq9bBH14GsDQQ59cgyxAQ IABR;
tyArray_w1HrpLTqYuul17OlwTATGw RSV5;
tyArray_wknELTfNGbUq9aI09bLKcmWQ IP;
tyArray_skVRt9aMy4p9aFnOi3BwXnJw RSV6;
NU32 STIR;
};
typedef NI32 tyEnum_IRQn_NM9bu6pz5ClFIBhSPR7mxgw;
N_NIMCALL(void, TIM2_IRQHandler)(void);
N_LIB_PRIVATE N_NIMCALL(void, mainProc2_rbimN4ouysYCcQ9cvzq9cqUA)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_stm32Init000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_stm32DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_volatileInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_volatileDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void);
NIM_CONST tyArray_GAcaPw08Gj9cXYhAaMMr9cfw TM_V45tF8B8NBcxFcjfe7lhBw_2 = {((NI) 1)}
;
NIM_CONST tyArray_GAcaPw08Gj9cXYhAaMMr9cfw TM_V45tF8B8NBcxFcjfe7lhBw_3 = {((NI) 0)}
;
NIM_CONST tyArray_GAcaPw08Gj9cXYhAaMMr9cfw TM_V45tF8B8NBcxFcjfe7lhBw_4 = {((NI) 17)}
;
NIM_CONST tyArray_HU7qaqKu9czJLT84iCBJnsA TM_V45tF8B8NBcxFcjfe7lhBw_5 = {((NI) 0),
((NI) 7)}
;
NIM_CONST tyArray_HU7qaqKu9czJLT84iCBJnsA TM_V45tF8B8NBcxFcjfe7lhBw_6 = {((NI) 0),
((NI) 1)}
;

N_NIMCALL(void, TIM2_IRQHandler)(void) {
	{
		NU32 res;
		NI ret;
		NU32 res_2;
		NI ret_2;
		NU32 res_3;
		NI ret_3;
		res = (NU32)0;
		res = (*(NU32 volatile*)(&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).SR));
		ret = ((NI) 0);
		{
			NI i;
			NI i_2;
			i = (NI)0;
			i_2 = ((NI) 0);
			{
				while (1) {
					if (!(i_2 < ((NI) 1))) goto LA5;
					i = TM_V45tF8B8NBcxFcjfe7lhBw_2[(i_2)- 0];
					ret = (NI)(ret | (NI)((NU32)(((NI) 1)) << (NU32)(i)));
					i_2 += ((NI) 1);
				} LA5: ;
			}
		}
		if (!!(((NU32)(res & ((NU32) (ret))) == ((NI) 0)))) goto LA6_;
		res_2 = (NU32)0;
		res_2 = (*(NU32 volatile*)(&(*((tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw*) 1207959552)).ODR));
		ret_2 = ((NI) 0);
		{
			NI i_3;
			NI i_4;
			i_3 = (NI)0;
			i_4 = ((NI) 0);
			{
				while (1) {
					if (!(i_4 < ((NI) 1))) goto LA10;
					i_3 = TM_V45tF8B8NBcxFcjfe7lhBw_3[(i_4)- 0];
					ret_2 = (NI)(ret_2 | (NI)((NU32)(((NI) 1)) << (NU32)(i_3)));
					i_4 += ((NI) 1);
				} LA10: ;
			}
		}
		*((NU32 volatile*)((&(*((tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw*) 1207959552)).ODR))) = ((NU32) ((NU32)(res_2 & (NU32)((NU32) ~(((NU32) (ret_2)))))));
		res_3 = (NU32)0;
		res_3 = (*(NU32 volatile*)(&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).SR));
		ret_3 = ((NI) 0);
		{
			NI i_5;
			NI i_6;
			i_5 = (NI)0;
			i_6 = ((NI) 0);
			{
				while (1) {
					if (!(i_6 < ((NI) 1))) goto LA13;
					i_5 = TM_V45tF8B8NBcxFcjfe7lhBw_2[(i_6)- 0];
					ret_3 = (NI)(ret_3 | (NI)((NU32)(((NI) 1)) << (NU32)(i_5)));
					i_6 += ((NI) 1);
				} LA13: ;
			}
		}
		*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).SR))) = ((NU32) ((NU32)(res_3 & (NU32)((NU32) ~(((NU32) (ret_3)))))));
	}
	LA6_: ;
	{
		NU32 res_4;
		NI ret_4;
		NU32 res_5;
		NI ret_5;
		NU32 res_6;
		NI ret_6;
		res_4 = (NU32)0;
		res_4 = (*(NU32 volatile*)(&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).SR));
		ret_4 = ((NI) 0);
		{
			NI i_7;
			NI i_8;
			i_7 = (NI)0;
			i_8 = ((NI) 0);
			{
				while (1) {
					if (!(i_8 < ((NI) 1))) goto LA18;
					i_7 = TM_V45tF8B8NBcxFcjfe7lhBw_3[(i_8)- 0];
					ret_4 = (NI)(ret_4 | (NI)((NU32)(((NI) 1)) << (NU32)(i_7)));
					i_8 += ((NI) 1);
				} LA18: ;
			}
		}
		if (!!(((NU32)(res_4 & ((NU32) (ret_4))) == ((NI) 0)))) goto LA19_;
		res_5 = (NU32)0;
		res_5 = (*(NU32 volatile*)(&(*((tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw*) 1207959552)).ODR));
		ret_5 = ((NI) 0);
		{
			NI i_9;
			NI i_10;
			i_9 = (NI)0;
			i_10 = ((NI) 0);
			{
				while (1) {
					if (!(i_10 < ((NI) 1))) goto LA23;
					i_9 = TM_V45tF8B8NBcxFcjfe7lhBw_3[(i_10)- 0];
					ret_5 = (NI)(ret_5 | (NI)((NU32)(((NI) 1)) << (NU32)(i_9)));
					i_10 += ((NI) 1);
				} LA23: ;
			}
		}
		*((NU32 volatile*)((&(*((tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw*) 1207959552)).ODR))) = ((NU32) ((NU32)(res_5 | ((NU32) (ret_5)))));
		res_6 = (NU32)0;
		res_6 = (*(NU32 volatile*)(&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).SR));
		ret_6 = ((NI) 0);
		{
			NI i_11;
			NI i_12;
			i_11 = (NI)0;
			i_12 = ((NI) 0);
			{
				while (1) {
					if (!(i_12 < ((NI) 1))) goto LA26;
					i_11 = TM_V45tF8B8NBcxFcjfe7lhBw_3[(i_12)- 0];
					ret_6 = (NI)(ret_6 | (NI)((NU32)(((NI) 1)) << (NU32)(i_11)));
					i_12 += ((NI) 1);
				} LA26: ;
			}
		}
		*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).SR))) = ((NU32) ((NU32)(res_6 & (NU32)((NU32) ~(((NU32) (ret_6)))))));
	}
	LA19_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, mainProc2_rbimN4ouysYCcQ9cvzq9cqUA)(void) {
	NU32 res;
	NI ret;
	NU32 res_2;
	NI ret_2;
	NU32 res_3;
	NI ret_3;
	NU32 res_4;
	NI ret_4;
	NU32 res_5;
	NI ret_5;
	NU32 res_6;
	NI ret_6;
	res = (NU32)0;
	res = (*(NU32 volatile*)(&(*((tyObject_st_rcc_MuzeLgc5IKig8i4T9bW3EeA*) 1073876992)).AHBENR));
	ret = ((NI) 0);
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < ((NI) 1))) goto LA3;
				i = TM_V45tF8B8NBcxFcjfe7lhBw_4[(i_2)- 0];
				ret = (NI)(ret | (NI)((NU32)(((NI) 1)) << (NU32)(i)));
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	*((NU32 volatile*)((&(*((tyObject_st_rcc_MuzeLgc5IKig8i4T9bW3EeA*) 1073876992)).AHBENR))) = ((NU32) ((NU32)(res | ((NU32) (ret)))));
	res_2 = (NU32)0;
	res_2 = (*(NU32 volatile*)(&(*((tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw*) 1207959552)).MODER));
	ret_2 = ((NI) 0);
	{
		NI i_3;
		NI i_4;
		i_3 = (NI)0;
		i_4 = ((NI) 0);
		{
			while (1) {
				if (!(i_4 < ((NI) 1))) goto LA6;
				i_3 = TM_V45tF8B8NBcxFcjfe7lhBw_3[(i_4)- 0];
				ret_2 = (NI)(ret_2 | (NI)((NU32)(((NI) 1)) << (NU32)(i_3)));
				i_4 += ((NI) 1);
			} LA6: ;
		}
	}
	*((NU32 volatile*)((&(*((tyObject_st_gpio_h1PU54W7WwiSvJVww2io9bw*) 1207959552)).MODER))) = ((NU32) ((NU32)(res_2 | ((NU32) (ret_2)))));
	res_3 = (NU32)0;
	res_3 = (*(NU32 volatile*)(&(*((tyObject_st_rcc_MuzeLgc5IKig8i4T9bW3EeA*) 1073876992)).APB1ENR));
	ret_3 = ((NI) 0);
	{
		NI i_5;
		NI i_6;
		i_5 = (NI)0;
		i_6 = ((NI) 0);
		{
			while (1) {
				if (!(i_6 < ((NI) 1))) goto LA9;
				i_5 = TM_V45tF8B8NBcxFcjfe7lhBw_3[(i_6)- 0];
				ret_3 = (NI)(ret_3 | (NI)((NU32)(((NI) 1)) << (NU32)(i_5)));
				i_6 += ((NI) 1);
			} LA9: ;
		}
	}
	*((NU32 volatile*)((&(*((tyObject_st_rcc_MuzeLgc5IKig8i4T9bW3EeA*) 1073876992)).APB1ENR))) = ((NU32) ((NU32)(res_3 | ((NU32) (ret_3)))));
	res_4 = (NU32)0;
	res_4 = (*(NU32 volatile*)(&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).CR1));
	ret_4 = ((NI) 0);
	{
		NI i_7;
		NI i_8;
		i_7 = (NI)0;
		i_8 = ((NI) 0);
		{
			while (1) {
				if (!(i_8 < ((NI) 2))) goto LA12;
				i_7 = TM_V45tF8B8NBcxFcjfe7lhBw_5[(i_8)- 0];
				ret_4 = (NI)(ret_4 | (NI)((NU32)(((NI) 1)) << (NU32)(i_7)));
				i_8 += ((NI) 1);
			} LA12: ;
		}
	}
	*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).CR1))) = ((NU32) ((NU32)(res_4 | ((NU32) (ret_4)))));
	res_5 = (NU32)0;
	res_5 = (*(NU32 volatile*)(&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).DIER));
	ret_5 = ((NI) 0);
	{
		NI i_9;
		NI i_10;
		i_9 = (NI)0;
		i_10 = ((NI) 0);
		{
			while (1) {
				if (!(i_10 < ((NI) 2))) goto LA15;
				i_9 = TM_V45tF8B8NBcxFcjfe7lhBw_6[(i_10)- 0];
				ret_5 = (NI)(ret_5 | (NI)((NU32)(((NI) 1)) << (NU32)(i_9)));
				i_10 += ((NI) 1);
			} LA15: ;
		}
	}
	*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).DIER))) = ((NU32) ((NU32)(res_5 | ((NU32) (ret_5)))));
	*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).PSC))) = ((NU32) (((NI) 8000)));
	*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).ARR))) = ((NU32) (((NI) 1000)));
	*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).CCR1))) = ((NU32) (((NI) 500)));
	res_6 = (NU32)0;
	res_6 = (*(NU32 volatile*)(&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).EGR));
	ret_6 = ((NI) 0);
	{
		NI i_11;
		NI i_12;
		i_11 = (NI)0;
		i_12 = ((NI) 0);
		{
			while (1) {
				if (!(i_12 < ((NI) 1))) goto LA18;
				i_11 = TM_V45tF8B8NBcxFcjfe7lhBw_3[(i_12)- 0];
				ret_6 = (NI)(ret_6 | (NI)((NU32)(((NI) 1)) << (NU32)(i_11)));
				i_12 += ((NI) 1);
			} LA18: ;
		}
	}
	*((NU32 volatile*)((&(*((tyObject_st_tim234_efIwa2Bl9bVZnQybiPg9cSbw*) 1073741824)).EGR))) = ((NU32) ((NU32)(res_6 | ((NU32) (ret_6)))));
	*((NU32 volatile*)((&(*((tyObject_st_nvic_89cdN5dIxFWwR88uhxVZzLw*) IL64(3758153984))).ISER[((NI)((NU32)(((NI) (((tyEnum_IRQn_NM9bu6pz5ClFIBhSPR7mxgw) 28)))) >> (NU32)(((NI) 5))))- 0]))) = ((NU32) ((NI)((NU32)(((NI) 1)) << (NU32)((NI)(((NI) (((tyEnum_IRQn_NM9bu6pz5ClFIBhSPR7mxgw) 28))) & ((NI) 31))))));
	{
		if (!(((NI) 0) <= ((NI) (((tyEnum_IRQn_NM9bu6pz5ClFIBhSPR7mxgw) 28))))) goto LA21_;
		*((NU8 volatile*)((&(*((tyObject_st_nvic_89cdN5dIxFWwR88uhxVZzLw*) IL64(3758153984))).IP[(((NU) (((tyEnum_IRQn_NM9bu6pz5ClFIBhSPR7mxgw) 28))))- 0]))) = ((NU8) ((NI)((NI)((NU32)(((NI) (((NI) 0)))) << (NU32)(((NI) 4))) & ((NI) 255))));
	}
	LA21_: ;
	{
		while (1) {
		}
	}
}
void PreMainInner(void) {
	systemInit000();
	unknown_stm32DatInit000();
	stdlib_volatileDatInit000();
	mainDatInit000();
	unknown_stm32Init000();
	stdlib_volatileInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
}

int main(void) {
	NimMain();
	return 0;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	mainProc2_rbimN4ouysYCcQ9cvzq9cqUA();
}

NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void) {
}

